Adding API Key for ZAP Check (KC)

diff --git a/infra/Jenkinsfile b/infra/Jenkinsfile
--- a/infra/Jenkinsfile
+++ b/infra/Jenkinsfile
@@ -95,20 +95,20 @@ pipeline {
 
 
               echo "Checking ZAP readiness"
-              for i in $(seq 1 24); do
-                if curl -sS "${ZAP_URL}/JSON/core/view/version/"; then
-                  echo "ZAP is up"
-                  ZAP_STATUS=1
-                  break
-                fi
-                echo "WARNING: ZAP not ready yet, rechecking in 5 seconds."
-                sleep 5
-              done
+                for i in $(seq 1 24); do
+                  if curl -sS "${ZAP_URL}/JSON/core/view/version/?apikey=${ZAP_API_KEY}" >/dev/null 2>&1; then
+                    echo "ZAP is up"
+                    ZAP_STATUS=1
+                    break
+                  fi
+                  echo "WARNING: ZAP not ready yet, rechecking in 5 seconds."
+                  sleep 5
+                done
 
-              if [ -z "$ZAP_STATUS" ]; then
-                echo "ERROR: ZAP container is not responding."
-                exit 1
-              fi
+                if [ -z "$ZAP_STATUS" ]; then
+                  echo "ERROR: ZAP container is not responding."
+                  exit 1
+                fi
 
               echo "Starting ZAP Spider"
               SPIDER_RESP=$(curl -s "${ZAP_URL}/JSON/spider/action/scan/?apikey=${ZAP_API_KEY}&url=${STAGE_URL}&maxChildren=0")
